### ISSUE TITLE
idea2018.2不可用

### ISSUE THREAD

**Issue by leyou240** [mustfun/mybatis-plugin-free#2]
如题，今天升级idea到最新版本2018.2之后。插件不能正常使用了。

**Comment by leyou240** [comment]
@mustfun

**Comment by nan-lou** [comment]
将com.github.mustfun.mybatis.plugin.definitionsearch.MapperDefinitionSearch类的processQuery方法参数
Processor<XmlElement>改为Processor<? super XmlElement>，plugin.xml since-build改为181.4892.42，重新编译即可，

**Comment by nan-lou** [comment]
对plugin开发略有兴趣，但是英文文档看得不大明白，又找不到中文文档，很伤脑筋qwq

**Comment by nan-lou** [comment]
对了，还有build.gradle intellij 的version改为IU-2018.2，（纯粹自己摸索，有误的地方还请不吝赐教）

**Comment by mustfun** [comment]
@nan-lou 加油，这是一条不归之路，另外已经升级了18.2可用的版本
